service: cart-nest-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  nestFunction:
    handler: dist/main.handler
    events:
     - http:
        method: ANY
        path: /
     - http:
        method: ANY
        path: '{proxy+}'

